//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Calendar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Person
    {
        public Person()
        {
            this.Attendances = new HashSet<Attendance>();
        }

        [Key]
        public System.Guid PersonID { get; set; }
        [StringLength(16, ErrorMessage = "First name can be no longer than 16 characters."),
        Required(ErrorMessage = "Please enter first name.")]
        public string FirstName { get; set; }
        [StringLength(16, ErrorMessage = "Last name can be no longer than 16 characters."),
        Required(ErrorMessage = "Please enter last name.")]
        public string LastName { get; set; }
        [StringLength(10, ErrorMessage = "User ID can be no longer than 10 characters."),
        Required(ErrorMessage = "Please enter user ID.")]
        public string UserID { get; set; }
        [Timestamp]
        public byte[] timestamp { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
    }
}
